export {
  getDex,
  getSpecies,
  getAllSpecies,
  getMove,
  getAllMoves,
  getAbility,
  getItem,
  getAllItems,
  searchItems,
  getLearnset,
  searchSpecies,
  getTypeChart,
  isMegaStone,
  getMegaStonesFor,
  getMegaForm,
  isZCrystal,
  getZCrystalType,
  getSignatureZCrystal,
  getGen9,
  getRawMove,
  getRawSpecies,
  getType,
  resolveSpeciesName,
} from "./dex.service"

export type * from "./types"
