import { z } from "zod"

export const chatMessageSchema = z.object({
  sessionId: z.string().optional(),
  message: z.string().min(1, "message is required"),
  teamId: z.string().optional(),
  formatId: z.string().optional(),
  context: z.unknown().optional(),
  contextMode: z.string().optional(),
  contextData: z.string().optional(),
  regenerate: z.boolean().optional(),
  autoAnalyzeDepth: z.enum(["quick", "deep"]).optional(),
  metadata: z
    .object({
      autoGenerated: z.boolean().optional(),
      turn: z.number().optional(),
      depth: z.enum(["quick", "deep"]).optional(),
    })
    .optional(),
})

export const chatSessionCreateSchema = z.object({
  teamId: z.string().optional(),
  contextMode: z.string().optional(),
  contextData: z.string().optional(),
})

export const chatSessionUpdateSchema = z.object({
  title: z.string().optional(),
})

export const chatSessionListSearchSchema = z.object({
  teamId: z.string().optional(),
  contextMode: z.string().optional(),
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(20),
})
